### ISSUE TITLE
geolocation error android

### ISSUE THREAD

**Issue by AnnNtY** [teerasej/flutter-handbook#2]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at
https://flutter.dev/go/android-project-migration
to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
lib\main.dart:1
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY .

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'META-INF/proguard/coroutines.pro'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by teerasej** [comment]
ขอบคุณครับ 

ตรวจสอบแล้ว เกิดจากการไม่ compatible ของเวอร์ชั่น flutter ในโปรเจคที่เราใช้ กับตัว package location 
ตอนนี้ได้ทำการแก้ไขตัว project และอัพเดตเนื้อหาใน [workshop ให้เป็นเวอร์ชั่นล่าสุด](https://github.com/teerasej/flutter-handbook/blob/master/geolocation/readme.md)แล้ว 

ก่อนใช้อย่าลืมรันคำสั่งอัพเป็น flutter 2.0.1 ด้วยคำสั่ง 

```bash
flutter upgrade 
```

ใน terminal หรือ command prompt นะครับ
